export interface ProjectResource {
  label: string;
  url: string;
  type: "image" | "pdf" | "html" | "link";
}

export interface Project {
  id: string;
  title: string;
  titleEn?: string;
  description: string;
  descriptionEn?: string;
  tags: string[];
  imageUrl?: string;
  thumbLabel?: string;
  link?: string;
  status: "live" | "beta" | "development" | "deployed";
  type: "company" | "team" | "personal";
  category: ("fullstack" | "backend" | "frontend" | "ai")[];
  company?: string;
  period: string;
  role: string;
  roleEn?: string;
  longDescription?: string;
  longDescriptionEn?: string;
  details: string[];
  roleDetails?: { role: string; items: string[] }[];
  achievements: string[];
  achievementsEn?: string[];
  resources?: ProjectResource[];
  hidden?: boolean;
  backendActive?: boolean;
  /** 발주처 납품 정규 프로젝트가 아닌 사내/개인 성격 작업 (카드에 별도 배지 표시) */
  internal?: boolean;
}

export const projects: Project[] = [
  {
    id: "nipa-satellite",
    title: "NIPA 위성 변화탐지 AI 플랫폼 - MSA 설계",
    titleEn: "NIPA Satellite Change Detection AI Platform - 9-Service MSA",
    description: "모놀리식 → MSA 전환으로 재배포 월 10건→1건. RabbitMQ 비동기 AI 파이프라인, Envoy Gateway · Keycloak OIDC 게이트웨이 인증을 구현한 위성 변화탐지 플랫폼.",
    descriptionEn: "Satellite change detection platform: monolith to 9-service MSA (monthly redeployments 10→1). RabbitMQ async AI pipeline, gateway-level auth via Envoy Gateway · Keycloak OIDC.",
    tags: ["RabbitMQ", "Next.js", "TypeScript", "CesiumJS", "FastAPI", "Go", "ONNX Runtime", "Kubernetes"],
    imageUrl: "/nipa_logo.svg",
    status: "deployed",
    type: "company",
    category: ["backend", "ai"],
    company: "한컴인스페이스",
    period: "2025.07 ~ 진행중",
    role: "백엔드 엔지니어",
    roleEn: "Backend Engineer",
    longDescription: "두 시점의 위성 영상을 비교해 지표 변화를 AI로 탐지하는 플랫폼. NIPA(정보통신산업진흥원) 지원 사업. MSA + FastAPI 기반으로 재설계했으며, RabbitMQ 비동기 파이프라인과 Next.js 15 FSD 프론트엔드를 처음 도입했습니다.",
    longDescriptionEn: "AI platform detecting surface changes by comparing satellite images from two time points. NIPA-funded. Redesigned with 9-service MSA + FastAPI, introducing RabbitMQ async pipeline and Next.js 15 FSD frontend for the first time.",
    details: [],
    roleDetails: [],
    achievements: [
      "[작업 유실] Salt 폴링 ack/nack 없어 노드 재시작 시 작업 RUNNING 고착 → RabbitMQ ack/nack + DLQ 비동기 파이프라인 전환 - 작업 유실 0건",
      "[단계별 확장] 단일 처리 구조로는 병목 단계만 선택적으로 확장 불가 → 수집·전처리·추론·후처리 단계별 큐 분리, 각 단계 워커를 독립적으로 스케일 - 처리 워커 1개→15개 수평 확장, 단계별 트래픽에 맞춘 자원 조절 구조 확보",
      "[배포 효율] 모놀리식으로 기능 하나 배포 시 전체 재시작 → MSA 분리, 전 서비스 FastAPI 전환, Nginx 라우팅 - 재배포 월 10건→1건, 배포 속도 4분→30초",
      "[메타 조회 성능] 위성영상 메타 조회 API가 ORM 풀 엔티티 하이드레이션과 중복 SRID 변환, 페이지네이션 부재로 대량 조회 시 응답이 느리고 크기도 예측 불가능 → 컬럼 프로젝션 전환, 중복 공간연산 제거, 화이트리스트 기반 동적 필터, page/limit 페이지네이션 도입 - 응답 속도·크기 통제 가능",
      "[db-api 계층화] FastAPI 튜토리얼 구조 그대로 사용해 테이블이 늘 때마다 models·crud·router 각 1개 파일에 로직이 누적 → 엔티티 단위 models·서비스 클래스 services·라우터 api 3계층으로 분리 - 이후 신규 리소스가 이 구조 위에서 확장",
      "[폐쇄망 분산 ID] 분리망 환경에서 외부 코디네이터 접근 불가, UUID로는 발생 서버 추적 불가 → Snowflake 알고리즘 직접 구현, worker ID에 망 정보 인코딩",
      "[프론트 유지보수] Thymeleaf 레거시에 기능 경계 없어 수정 영향 범위 예측 불가 → Next.js 15 + FSD 전면 마이그레이션, CesiumJS 커스텀 ImageryProvider - MVT·MBTiles·ImageLayer 이종 레이어 단일 인터페이스 추상화",
    ],
    achievementsEn: [
      "[Job Loss] Salt polling with no ack/nack caused tasks stuck in RUNNING on node restart → Switched to RabbitMQ ack/nack + DLQ async pipeline - 0 job losses",
      "[Staged Scaling] A single processing pipeline couldn't scale just the bottleneck stage → split collection/preprocessing/inference/postprocessing into separate queues, scaling each stage's workers independently - horizontally scaled processing workers from 1 to 15, tuning resources per stage to traffic",
      "[Deploy Efficiency] Monolithic deployment required full restart per feature → Split into 9 MSA, migrated all services to FastAPI, routed via Nginx - deployments reduced from 10/month to 1, deploy time 4min→30s",
      "[Metadata Query Performance] Satellite metadata query API suffered from full ORM entity hydration, redundant SRID conversion, and no pagination, making response time and size unpredictable at scale → switched to column projection, removed redundant spatial ops, added whitelist-based dynamic filtering and page/limit pagination - made response speed and size controllable",
      "[db-api Layering] db-api kept the original FastAPI tutorial structure, piling logic into single models/crud/router files as tables grew → split into 3 layers - per-entity models, service classes in services, routers in api - later features scaled on top of this pattern",
      "[Isolated-network Distributed ID] No external coordinator in air-gapped network, UUID couldn't identify originating server → Implemented Snowflake algorithm from scratch, encoded network info into worker ID",
      "[Frontend Maintainability] Thymeleaf legacy with no feature boundaries made change impact unpredictable → Full migration to Next.js 15 + FSD, CesiumJS custom ImageryProvider - MVT·MBTiles·ImageLayer abstracted into single interface",
    ],
    resources: [
      { label: "NIPA 로고", url: "/nipa_logo.svg", type: "image" },
      { label: "웹 화면", url: "/gis-platform_thum.png", type: "image" },
    ],
  },
  {
    id: "kari-satellite",
    title: "항공우주연구원 위성영상 AI 처리 플랫폼 구축",
    titleEn: "KARI Satellite Imagery AI Processing Platform",
    description: "10개 이상 위성 소스를 수집·처리해 AI 추론 결과를 CesiumJS로 가시화하는 위성영상 AI 처리 플랫폼. 한국항공우주연구원 납품.",
    descriptionEn: "AI processing platform collecting 10+ satellite sources and visualizing inference results (object detection, segmentation, super-resolution) via CesiumJS. Delivered to Korea Aerospace Research Institute (KARI).",
    tags: ["Spring Boot", "Go", "PyTorch", "FastAPI", "ONNX Runtime", "Kubernetes", "Aliyun GPUShare", "MyBatis", "Redis", "Salt-Stack", "Nginx"],
    imageUrl: "/kari_logo.svg",
    status: "deployed",
    type: "company",
    category: ["backend", "ai"],
    company: "한컴인스페이스",
    period: "2023.10 ~ 2025.07",
    role: "백엔드 엔지니어",
    roleEn: "Backend Engineer",
    longDescription: "다누리·Sentinel·Landsat 등 10개 이상 위성 소스를 수집·처리해 객체탐지·세그멘테이션·초해상도 AI 추론 결과를 CesiumJS 뷰어로 가시화하는 플랫폼. 한국항공우주연구원 납품. Outbox 패턴 라이브러리, CDC 이벤트 멱등키 설계, Aliyun GPUShare, janus 워크플로우 엔진, SaltStack 기반 K8s 운영 안정화를 이 프로젝트에서 설계·구현했습니다.",
    longDescriptionEn: "Platform collecting and processing 10+ satellite sources (Danuri, Sentinel, Landsat, etc.) and visualizing object detection, segmentation, and super-resolution AI results via CesiumJS viewer. Delivered to KARI. Designed and implemented the Outbox pattern library, Aliyun GPUShare integration, and janus workflow engine in this project.",
    details: [],
    roleDetails: [],
    achievements: [
      "[이벤트 유실] Debezium replication slot 반복 파손으로 전체 스냅샷 재수행 → AOP + MyBatis Outbox 라이브러리 직접 개발 - CDC 인프라 의존 제거, 이벤트 유실 0건",
      "[GPU 활용] 1파드=1GPU 강제로 자원 90% 유휴 → Aliyun GPUShare aliyun.com/gpu-mem 단위 분할 - GPU 4장에서 70파드 병렬 추론, 일 처리량 200건→3,000건",
      "[AI 모델] YOLOv11m OBB/HBB 이원 탐지 20클래스 (HBB mAP50 0.644 / OBB 0.604), UPerNet+ConvNeXt 세그멘테이션 mIoU 0.7205 - 회전 augmentation 역효과 확인·제거, 색감 도메인 매칭 전처리 구현",
      "[위성 소스 통합] 소스별 하드코딩으로 신규 위성 추가 시 파이프라인 전체 수정 → janus H_BASE/S_BASE 추상화, 10+ 소스 단일 파이프라인 - 신규 소스 추가 코드 수정 0건",
      "[API 성능] PostGIS 전수 연산으로 위성 메타 API 38초 소요, 조회 API에서 여러 테이블을 매번 별도 트랜잭션으로 조회해 HikariCP 커넥션 추가 점유 → 조건부 실행 + 페이징 + Redis 캐싱 + 알람 로그 인덱스(idx_alam_log_sno·idx_reg_dt) 추가, 여러 테이블 조회를 단일 트랜잭션으로 통합 - 159ms(239배), 50VU 에러율 11.22%→0%",
      "[무외래키 스키마 설계] 위성 메타·추론 결과 테이블 로우 증가로 향후 샤딩 필요성 예상, 외래키는 샤딩 시 걸림돌이 됨 → 정합성이 깨져도 치명적이지 않은 관측·추론 결과성 데이터에 한해 외래키 제약을 두지 않는 스키마로 설계 - DB 레벨 엄격한 정합성보다 스키마 유연성을 우선한 선제적 트레이드오프",
      "[유저 생성 정합성 버그] 외래키가 없어 정합성을 트랜잭션 경계로 대신 지켜야 하는데, 유저 생성 시 유저·권한 insert가 각각 별도 트랜잭션으로 실행돼 한쪽만 실패하면 유저-권한 불일치가 발생할 수 있었음 → 두 insert를 하나의 트랜잭션으로 묶어 원자성 확보",
      "[Debezium 자가치유] PostgreSQL replication slot이 WAL 유실·비활성 상태로 남아 CDC가 정지하는 장애 반복, 상태 판정 우선순위 버그로 필요한 slot 재생성이 누락됨 → 상태 판정 순서 재정렬, 강제종료→slot 재생성→검증까지 자동 복구하는 자가치유 함수 구현 - 재시도 폭주 없는 CDC 파이프라인 자가치유 구조 확보",
      "[SaltStack K8s 운영] K8s 기본 스케줄러가 노드별 메모리 사용률을 실시간 반영 못해 특정 노드에 AI 워크로드가 몰려 OOM 발생, 정작 배치를 담당하는 SaltStack master 파드 자체도 무거운 livenessProbe가 probe timeout과 충돌해 CrashLoopBackOff 반복 → SaltStack Minion으로 노드 상태 실시간 점검 후 메모리 50% 미만 노드에만 워크로드 자동 할당, 헬스체크는 프로세스 생존 확인(pgrep)만으로 경량화 - 노드 과부하·OOM 사전 차단과 파드 안정성 동시 확보",
      "[다운로드 동시성 버그] goroutine+channel 기반 산출물 압축 다운로드가 타임아웃 시 채널 close와 결과 전송이 경쟁해 panic 위험, Range(재개 다운로드) 요청도 미지원 → 압축 결과를 임시파일 원자적 rename으로 캐싱, 채널 기반 동시성 코드를 제거하고 HTTP Range 지원 방식으로 재작성 - 경쟁조건 제거, 캐시 응답으로 재압축 회피, 재개 다운로드 지원",
      "[CDC 이벤트 중복] 재전달된 CDC 이벤트가 타임스탬프 컬럼 차이로 매번 다른 값 취급되어 중복 반영, 원본 payload 얕은 참조로 처리 중 오염도 발생 → 휘발성 컬럼 제외 정렬 payload를 자연키로 쓰는 멱등키 설계, deepcopy로 참조 분리 - 23개 테이블 CDC 반영을 단일 dedup 로직으로 안전 처리",
      "[CDC 이진 데이터 정합성] bytea 컬럼이 SQLAlchemy 모델에 String으로 잘못 선언돼 Postgres 원본과 타입 불일치, 1차 수정도 실제 base64 디코딩 없이 문자열→UTF-8 바이트 변환만 해 이미지가 계속 깨짐 → 컬럼 타입을 LargeBinary로 재정의하고 base64.b64decode()로 정정, Debezium 소스 설정에 binary.handling.mode=base64 명시, base64 실패 시 hex 디코딩 폴백 추가 - 타입 선언→인코딩→디코딩 3단 계층 일관 처리",
      "[EWKB 파싱 안정화] PostGIS EWKB를 일반 WKB 파서로 처리하며 SRID 유무를 바이트 오프셋·비트마스크로 직접 잘라내 지오메트리 타입·엔디안 조합에 따라 간헐적 파싱 실패, 좌표 소수점 표현도 Go·Python이 달라 CDC 멱등키 매칭까지 영향 → Go는 go-geom의 wkb를 ewkb로 교체, Python은 shapely.wkb + rounding_precision=16으로 좌표 포맷 통일 - 수동 바이너리 파싱 코드 제거, 멱등키 매칭 안정성 확보",
    ],
    achievementsEn: [
      "[Event Loss] Repeated Debezium replication slot failures triggered full snapshots → Developed AOP + MyBatis Outbox library in-house - eliminated CDC infrastructure dependency, 0 event losses",
      "[GPU Utilization] 1-pod-per-GPU forced 90% resource idle → Aliyun GPUShare gpu-mem unit partitioning - 70 pods parallel inference on 4 GPUs, daily throughput 200→3,000 jobs",
      "[AI Model] YOLOv11m dual OBB/HBB detection 20 classes (HBB mAP50 0.644 / OBB 0.604), UPerNet+ConvNeXt segmentation mIoU 0.7205 - identified and removed rotation augmentation side effects, implemented color domain matching preprocessing",
      "[Satellite Source Integration] Per-source hardcoding required full pipeline rewrite for each new satellite → janus H_BASE/S_BASE abstraction, 10+ sources on single pipeline - 0 code changes needed for new source additions",
      "[API Performance] PostGIS full-scan satellite metadata API took 38s, and a query API opened a separate transaction per table it read, hogging extra HikariCP connections → conditional execution + pagination + Redis caching + added indexes on the alarm log table (idx_alam_log_sno, idx_reg_dt), plus consolidated multi-table reads into a single transaction - 159ms (239×), 50VU error rate 11.22%→0%",
      "[FK-less Schema Design] Row counts on satellite-metadata and inference-result tables kept growing, foreseeing a future need to shard - but foreign keys become a blocker once a referenced table moves to a different shard → deliberately left out FK constraints on tables holding observational/inference-result data where broken referential integrity isn't critical - a preemptive tradeoff favoring schema flexibility over strict DB-level consistency",
      "[User Creation Consistency Bug] With no foreign keys, referential integrity had to be enforced via transaction boundaries instead - but user creation ran the user insert and the permission insert as two separate transactions, so a failure in either could leave a user with no permissions or vice versa → wrapped both inserts in a single transaction to guarantee atomicity",
      "[Debezium Self-Healing] PostgreSQL replication slots repeatedly went WAL-lost/inactive, halting CDC, due to a state-priority bug that skipped required slot recreation → reordered the state-priority check and implemented an automated force-disconnect → recreate → verify recovery routine - self-healing CDC pipeline with no retry storms",
      "[SaltStack K8s Operations] The default K8s scheduler ignored real-time node memory usage and piled AI workloads onto already-loaded nodes causing OOM, while the SaltStack master pod itself kept crash-looping from a heavy livenessProbe colliding with its timeout → had SaltStack Minions check node status in real time and only schedule onto nodes under 50% memory, and slimmed the healthcheck to a plain process-liveness (pgrep) check - eliminated node overload/OOM and stabilized the pod simultaneously",
      "[Download Concurrency Bug] A goroutine+channel-based artifact-download/compression path risked a panic from a close-vs-send race on timeout, and had no support for resumable Range requests → cached compressed output via atomic temp-file rename and rewrote the concurrency away in favor of HTTP Range support - eliminated the race condition, avoided recompression via cache hits, and enabled resumable downloads",
      "[CDC Event Duplication] Redelivered CDC events were treated as distinct due to timestamp-column differences, causing duplicate writes, plus a shallow-reference bug corrupted the original payload mid-processing → designed an idempotent key from a sorted payload excluding volatile columns, and switched to deepcopy to isolate references - a single dedup path now safely handles CDC replication for 23 tables",
      "[CDC Binary Data Integrity] A bytea column was mis-declared as String in the SQLAlchemy model, mismatching the Postgres source, and even the first fix skipped real base64 decoding (just string→UTF-8 bytes), so images kept coming out corrupted → redefined the column as LargeBinary with proper base64.b64decode(), pinned Debezium's binary.handling.mode to base64 at the source, and added a hex-decode fallback for base64 failures - consistent handling across the type declaration → encoding → decoding chain",
      "[EWKB Parsing Stability] PostGIS EWKB was parsed with a plain WKB parser, manually stripping the SRID flag via byte-offset/bitmasking, which intermittently failed depending on geometry type/endianness, and inconsistent coordinate decimal formatting between Go and Python risked breaking CDC idempotent-key matching → swapped Go's wkb decoder for ewkb, and unified coordinate precision to 16 digits via shapely.wkb on the Python side - removed manual binary-parsing code and secured idempotent-key matching stability",
    ],
    resources: [
      { label: "로고", url: "/kari_logo.svg", type: "image" },
      { label: "플랫폼 소개", url: "/kari_intro.png", type: "image" },
      { label: "웹 화면", url: "/kari_web.png", type: "image" },
      { label: "샘플 Outbox", url: "https://github.com/Ahnyeongjun/outbox_module", type: "link" },
    ],
  },
  {
    id: "insops-satellite",
    title: "국가보안기관 위성영상 AI 처리 플랫폼 - 개발·운영·신규 구축",
    titleEn: "National Security Agency Satellite Imagery AI Platform - Development, Operations & Greenfield Build",
    description: "국가보안기관 위성영상 시스템을 프론트엔드·API 개발부터 에어갭 무중단 운영, 신규 플랫폼 구축까지 4년간 담당한 프로젝트.",
    descriptionEn: "Owned a national security agency satellite imagery system for 4 years - frontend/API development, air-gapped zero-downtime operations, and a greenfield platform build.",
    tags: ["Kubernetes", "Docker", "Rocky Linux", "NVMe Storage", "Go", "PostgreSQL", "GDAL", "Zabbix", "Shell", "Spring Boot", "Java", "MyBatis", "PostGIS", "CesiumJS", "JSP", "JWT"],
    imageUrl: "/hancominpsace_logo.png",
    status: "deployed",
    type: "company",
    category: ["fullstack", "backend"],
    company: "한컴인스페이스",
    period: "2022.05 ~ 진행중",
    role: "풀스택 개발 → 시스템 운영·인프라 구축",
    roleEn: "Full-Stack → Systems Operations & Infra",
    longDescription: "위성영상을 수집·판독해 정식 보고서로 만들어내는 국가보안기관 대상 시스템입니다. 초기 2년은 분석관이 CesiumJS 3D globe 위에서 표적을 판독해 정부 표준 문서(HWP)로 보고서를 산출하는 화면의 프론트엔드·API를 end-to-end로 개발했으며, 인증·인가 체계와 Rate Limiting·CSP·SQL Injection 대응 등 보안 체계를 직접 설계했습니다. 이후 다종 위성 포맷을 통합 관리하고 해상도 향상(Pansharpening)·웹 가시화 가공을 거쳐 배포하는 플랫폼의 운영을 맡아, 인터넷이 완전히 차단된 에어갭 환경에서 수십 대 서버 규모 클러스터를 무중단 운영했습니다(2024.07~). 이어서 별도의 다종위성 수집·처리 플랫폼을 물리 베어메탈 서버 설치부터 K8s 클러스터 구성, DB 설계, 파이프라인 구현, Go 타일 서버 동시성 설계까지 전 과정 신규 구축했습니다(2025.06~2025.12).",
    longDescriptionEn: "A national security agency system that collects and interprets satellite imagery to produce formal reports. For the first two years, built the frontend and API end-to-end for screens where analysts interpret targets on a CesiumJS 3D globe and produce Korea's government-standard HWP reports, while also designing the authentication/authorization system and security hardening (rate limiting, CSP, SQL injection defenses). Then took over operations for a platform unifying multi-satellite formats with pansharpening and web-visualization processing, running a several-dozen-server cluster with zero downtime in a fully air-gapped environment (2024.07-). Subsequently led a greenfield build of a separate multi-satellite ingestion/processing platform end to end - bare-metal server setup, K8s cluster configuration, DB design, pipeline implementation, and Go tile-server concurrency design (2025.06-2025.12).",
    details: [],
    roleDetails: [],
    achievements: [
      "[인증·인가 체계 설계] 엔드포인트가 늘수록 컨트롤러마다 권한 체크 코드가 흩어져 누락·중복 위험 증가, 토큰 단방향 저장만으로는 사용자별 활성 세션 수를 답할 수 없어 동시 로그인 통제·로그인 시도 방어도 불가 → 인증은 Spring Security 필터 체인, 인가는 커스텀 어노테이션+AOP로 선언적 분리, user→token 역색인을 Redis에 저장해 세션 즉시 조회·통제·로그인 실패 IP/계정 단위 카운트 후 TTL 자동 차단 - 신규 API는 어노테이션만 붙이면 권한 검증 적용",
      "[판독보고서] 별도 문서 도구 없이 영상 판독과 보고서 작성을 한 화면에서 끝낼 수 있게 구현(분석관 호평) → 페이지별 3D globe 화면 캡처가 그대로 HWP 배경으로 삽입되는 구조라 CesiumJS 카메라 rect 계산 기반 뷰 북마크·복귀 기능 구현",
      "[대용량 다운로드] ins-file-svr에서 이어받기(Range) 요청마다 DRM 재암호화가 일어나 조각마다 바이트 구조가 달라지며 파일이 깨짐 → synchronized 처리 + 암호화 파일 캐싱으로 최초 요청에만 암호화하도록 수정",
      "[다운로드 UX 재설계] 네트워크 끊기면 처음부터 재다운로드, 진행률 표시도 없음 → File System Access API 청크 스트리밍 + Range 이어받기·재시도 다운로더 구현 - 완성 후 코드 리뷰로 서버 folderDownload()가 Accept-Ranges 헤더만 선언할 뿐 실제 Range 파싱이 없어 매번 전체 재전송되는 구현 갭을 직접 발견",
      "[표적 데이터 무결성] 표적 생성·수정·삭제 이력 추적 불가, 참조 중인 표적 삭제 시 정합성 붕괴, 삭제된 표적을 가리키는 즐겨찾기가 고아 레코드로 남음 → CUD마다 이력 기록하는 감사로그 패턴 도입, 참조 카운트 사전 검증으로 삭제 차단, 삭제·이관 시 연관 즐겨찾기까지 계단식 정리 - 즐겨찾기 재정렬은 부분 시프트 + 윈도우 함수 재계산으로 전체 UPDATE 비용 제거",
      "[클라우드 배포 안정화] 리버스 프록시 뒤에서 클라우드 환경 배포 때마다 내부 API 연동이 끊기는 장애가 6일~2개월 간격으로 8회 반복 → application-cloud.yml 신설로 context-path·외부 API host를 환경별 분리, 내부 호출을 localhost+path prefix로 우회 - 반복 장애 재발 차단",
      "[컴포넌트 매니저] 팝업·iframe·인페이지 컴포넌트마다 통신 방식이 달라 호출 코드가 제각각 → execute() 하나로 위치와 무관하게 호출 가능한 공통 매니저 활용·개선, 창 경계를 넘는 함수 호출을 RPC처럼 추상화",
      "[base 모듈 · MyBatis 코드 생성] 테이블 수가 많아(40여 개) 신규 테이블마다 Entity·MyBatis XML mapper와 CRUD 계층을 손으로 반복 작성해야 함 → CRUD Controller·Service·Mapper·Entity를 제네릭 기반으로 추상화한 base 모듈을 구현해 상속만으로 재사용하도록 구성, DB information_schema를 조회해 컬럼 타입·PK·주석 기반으로 Entity(Entity/ReqData/Result/Search)와 CRUD·검색 XML mapper를 자동 생성하는 도구까지 팀 내부에 구축 - AOP 기반 공통 에러 로깅도 함께 적용",
      "[인증 마이그레이션] 세션·쿠키 기반 인증은 팝업·iframe 등 다중 창 구조에서 세션 공유가 번거롭고 신규 서비스 분리에도 제약 → 인증/인가 API를 토큰 기반으로 재개발·마이그레이션하며 점진적으로 모듈을 분리해 장애 전파를 최소화 - 코드 재활용 증가",
      "[가시화 장애 대응] 가시화 작업이 전부 'No space left on device'로 실패했지만 마운트 용량은 충분했고, 별도로 수억 픽셀 규모 위성영상을 통째로 메모리에 올리다 컨테이너가 OOM으로 강제 종료되는 문제도 있었음 → 스토리지 장애는 마운트 경로 직접 쓰기 테스트로 컨테이너가 아닌 스토리지 자체 문제로 특정 후 NVMe 상태와 업체 운영 코드까지 추적해 펌웨어 업그레이드 시 데이터 이동 로직 누락을 근본 원인으로 확정(임시 패치 후 정식 패치 연동), OOM은 픽셀 수 기준 일반·대용량 처리 경로 분기 후 GDAL 파이프라인으로 먼저 축소 - 두 장애 모두 자원이 부족한 환경에서도 구조적으로 작업이 진행되도록 개선",
      "[장애 사전 감지] 인터넷이 차단된 환경이라 장애를 사후에야 인지하는 구조 → Zabbix 커스텀 대시보드로 호스트·서비스 모니터링 체계 구축, 에러 검색 서비스와 sh 스크립트 기반 에러 감지를 함께 마련해 외부 검색 없이도 로그에서 바로 원인을 추적 - 외부 레퍼런스 없이 시스템 하부 레이어까지 추적하는 트러블슈팅 역량과 장애 사전 감지 체계 확보",
      "[DB 접근 계층 중앙화] 서비스마다 ORM으로 DB에 직접 접근해 스키마 변경 시 여러 서비스를 동시 수정해야 했고, Python ORM과 Go의 접근 패턴도 서로 어긋남 → 신규 구축 프로젝트에서 DB 접근을 Go 기반 API 한 곳으로 중앙화, 모든 서비스가 HTTP로만 DB에 접근하도록 재설계 - 스키마 변경 영향 범위를 API 레이어 한 곳으로 축소, 언어와 무관하게 동일한 방식으로 DB 접근",
      "[베어메탈 신규 구축] 관리형 인프라 없이 베어메탈부터 시작해야 하는 신규 구축 프로젝트 → 물리 서버 설치, K8s 클러스터 구성, 다종 수집기 통합·DB 기반 중복 체크·zst/tar.gz 포맷 변환 자동화까지 전 과정 직접 주도 - 베어메탈에서 운영 가능한 시스템까지 인프라 전 과정을 완주",
      "[Rate Limiting] 고위험 엔드포인트와 단순 조회 API가 동일하게 무제한 호출 가능, 로그인 무차별 대입 방어도 없었음 → 필터+AOP 2계층 위험도 기반 제한(HIGH 5회/분~MEDIUM 20회/분), Redis INCR 락-프리 로그인 실패 카운팅, Redis 장애 시 로그인은 막지 않는 fail-open 정책 - 경쟁조건 없이 위험도별 차등 제한 확보",
      "[보안 진단 대응] 외부 보안 진단에서 CSP 미비·SQL Injection 등 10건 이상 지적, CesiumJS의 eval 의존성 때문에 CSP를 강하게 걸면 지도 화면이 깨지는 제약 → CSP를 API origin 기반 런타임 동적 생성으로 전환, CesiumJS eval 패턴 직접 패치로 서드파티 제약 우회, 13개 매퍼 SQL Injection을 파라미터 바인딩으로 전환 - 보안 지적사항 해소, 잔존 리스크(동적 정렬 컬럼)는 별도 인지",
      "[다종위성 타일 서버 동시성] 위성·항공·월면 다중 레이어 GDAL 워핑 응답이 순차 처리로 지연, 무제한 goroutine 병렬화 도입 후 문제 발생으로 2차례 원복 → CPU 코어 기반 동적 세마포어로 동시 실행 수 제한, 요청 타임아웃·TTL 캐시·버퍼 풀·수동 GC 결합 - 두 차례 실패를 거쳐 안전한 병렬 처리 구조로 정착",
    ],
    achievementsEn: [
      "[Auth & Session Design] Permission checks scattered across controllers as endpoints grew, and unidirectional token storage couldn't answer 'how many sessions is this user in,' blocking concurrent-login control and brute-force defense → authentication in one Spring Security filter chain, authorization split out declaratively via custom annotation+AOP, and a Redis user→token reverse index for instant session lookup/control with per-IP/account login-failure counting and TTL-based auto-expiry lockout - new endpoints get permission checks just by adding the annotation",
      "[Interpretation Report] Built a report-authoring flow letting analysts go from imagery interpretation to a finished report in one screen, without a separate document tool (well received by analysts) → each page embeds a captured 3D globe screenshot as its HWP background, so implemented camera-rectangle-based view bookmarking/restore in CesiumJS",
      "[Large File Download] In ins-file-svr, each resumed Range request re-ran DRM encryption, so chunks landed with different byte layouts and corrupted the reassembled file → fixed by serializing downloads with synchronized and caching the encrypted file so encryption only runs on the first chunk",
      "[Download UX Redesign] Network drops meant restarting the whole download from scratch, with no progress indicator → built a File System Access API chunked-streaming downloader with Range-based resume and retry - after shipping it, a code review of the server's own folderDownload() surfaced that it declared Accept-Ranges but never actually parsed the header, silently re-sending the full file every time",
      "[Target Data Integrity] No audit trail for target creation/edit/deletion, deleting a referenced target broke referential integrity, and orphaned favorites pointed at deleted targets → added a CUD-level audit log, pre-validated reference counts to block deletion of referenced targets, and cascaded favorite cleanup on delete/transfer - favorite reordering itself now uses partial-range updates plus window-function renumbering instead of full-table updates",
      "[Cloud Deployment Stabilization] Deploying behind a reverse proxy into the client's cloud environment kept breaking internal API connectivity, requiring 8 fixes over 6-day-to-2-month intervals → introduced application-cloud.yml to separate context-path and external API hosts per environment, routing internal calls through localhost + path prefixes - stopped the recurring failure for good",
      "[Component Manager] Popups, iframes, and in-page components each communicated differently, fragmenting call code → leveraged and improved a shared manager exposing one execute() call regardless of component location, abstracting cross-window function calls like an RPC",
      "[base Module · MyBatis Code Generation] Manually writing an Entity class, MyBatis XML mapper, and full CRUD layer for every new table (of ~40) didn't scale → built a generic base module abstracting CRUD controller/service/mapper/entity for reuse via inheritance, plus an internal tool that queries the DB's information_schema (column types, PK, comments) to auto-generate Entity classes (Entity/ReqData/Result/Search) and CRUD/search XML mappers - also applied common AOP-based error logging across the base module",
      "[Auth Migration] Session/cookie-based auth made session sharing across popups/iframes cumbersome and constrained splitting out new services → redeveloped and migrated the auth/authorization API to token-based auth, progressively splitting modules to minimize failure propagation - increased code reuse",
      "[Visualization Incident Response] All visualization jobs failed with 'No space left on device' despite the mount showing free capacity, and separately, multi-hundred-megapixel satellite imagery force-killed containers with OOM → for the storage fault, isolated it to the storage device itself via a direct write test, then traced through NVMe status and the vendor's operating code to a missing firmware-upgrade data-migration step (hotfix then official patch); for OOM, branched processing into standard/large-image paths by pixel count and downsampled large images via a GDAL pipeline - both kept processing structurally viable under constrained resources",
      "[Proactive Incident Detection] The air-gapped environment meant incidents were only discovered after the fact → built a Zabbix host/service monitoring setup with custom dashboards, plus an internal error-search service and shell-script-based error detection so root causes could be traced straight from logs without external search - established troubleshooting skills that trace root causes down through system layers with no external references, plus proactive incident detection",
      "[DB Access Layer Centralization] Each service accessed the DB directly via its own ORM, so schema changes required touching multiple services at once, and Python's ORM and Go's access patterns diverged → on the greenfield build, centralized all DB access behind a single Go-based API, redesigning every service to talk to the DB only over HTTP - narrowed the blast radius of schema changes to one API layer and unified DB access across languages",
      "[Greenfield Infrastructure] A new-build project starting from bare metal with no managed infrastructure → drove the entire process directly - physical server setup, K8s cluster configuration, multi-collector integration, DB-based duplicate detection, and zst/tar.gz format conversion automation - carried infrastructure end-to-end from bare metal to an operable system",
      "[Rate Limiting] High-risk endpoints (upload/delete) and plain read APIs were equally unlimited, with no brute-force login defense → 2-layer filter+AOP risk-based limiting (HIGH 5/min ~ MEDIUM 20/min), lock-free login-failure counting via Redis INCR, and an explicit fail-open policy so Redis outages don't block logins - race-condition-free tiered limiting by endpoint risk",
      "[Security Hardening] An external security audit flagged 10+ issues (weak CSP, SQL injection), complicated by CesiumJS's eval dependency breaking the map view under a strict CSP → switched CSP to runtime dynamic generation keyed on API origin, patched CesiumJS's eval pattern directly to work around the third-party constraint, and converted 13 mappers' SQL injection surface to parameter binding - resolved the audit findings while explicitly flagging remaining risk in dynamic-sort columns",
      "[Multi-Satellite Tile Server Concurrency] GDAL warping across multi-layer satellite/aerial/lunar imagery was slow under sequential processing, and unbounded goroutine parallelism caused failures reverted twice → limited concurrency with a CPU-core-based dynamic semaphore, combined with request timeouts, a TTL cache, buffer pooling, and manual GC - settled on safe parallelism after two failed attempts",
    ],
  },
  {
    id: "team-mcp-agent",
    title: "Git · 캘린더 · HRWeb 통합 MCP 에이전트 개발",
    titleEn: "Git · Calendar · HRWeb Integrated MCP Agent",
    description: "FastMCP 기반 Gmail·캘린더·Git·HRWeb 통합 자동화 에이전트",
    descriptionEn: "FastMCP-based Gmail · Calendar · Git · HRWeb automation agent - actively used by a 10-person team",
    tags: ["Python", "FastMCP", "MCP", "Playwright", "Gmail API", "Google Calendar API"],
    imageUrl: "/hancominpsace_logo.png",
    status: "deployed",
    type: "company",
    internal: true,
    company: "한컴인스페이스",
    category: ["backend", "ai"],
    period: "2026.03 ~ 2026.04",
    role: "설계 및 개발",
    roleEn: "Design & Development",
    longDescription: "주간보고 작성, 일정 관리, 사내 HRWeb 입력 등 반복 업무를 자동화하기 위해 개인적으로 개발하여 공유한 MCP 기반 에이전트입니다. FastMCP로 8개 도구를 구현하고 Cursor·Claude Desktop에서 바로 호출할 수 있도록 연동했습니다.",
    longDescriptionEn: "MCP-based agent developed personally to automate repetitive tasks - weekly reports, schedule management, in-house HRWeb timesheet input - then shared with the entire 10-person team. Implemented 8 tools with FastMCP and integrated for direct invocation from Cursor and Claude Desktop.",
    details: [],
    roleDetails: [
      {
        role: "MCP 에이전트 설계 및 개발",
        items: [
          "FastMCP 기반 8개 도구 구현 - list_commits·get_trips·create_calendar_event·generate_report·send_report·upload_hrweb 등, Cursor·Claude Desktop에서 호출 가능",
          "Git subprocess로 리포별 커밋 로그 수집 → 폴더 단위 그룹핑, Google Calendar OAuth로 출장 일정 조회 → 두 소스를 병합해 주간보고 초안 자동 생성 후 Gmail SMTP로 발송",
          "엑셀 템플릿을 ZIP 내 XML 레벨로 직접 조작 - 서식·수식 100% 보존하면서 C열 카테고리 자동 감지 후 D/H 셀에 내용 주입",
          "사내 HRWeb(아마란스) Playwright 자동화 - 로그인 → 월 선택 → 날짜·프로젝트·공수 입력까지 전 흐름 브라우저 자동화, Git 커밋이 없는 날은 주변 커밋 패턴으로 description 추론",
        ],
      },
    ],
    achievements: [
      "반복 수작업으로 30분~1시간이 소요되던 주간보고 작성과 HRWeb 공수 입력 업무를 FastMCP 에이전트로 전 과정 자동화 - Git 커밋+캘린더 병합 → 엑셀 생성 → Gmail 발송까지 단일 명령으로 처리",
      "개인 도구에 그치지 않고 Claude Desktop·Cursor에서 바로 호출 가능하도록 공유",
      "[Jira·Bitbucket 자동화] 티켓 생성 후 브랜치 생성·PR 작성까지 매번 수작업으로 이어지던 흐름 → 티켓 상태 변경 시 규칙 기반으로 브랜치를 자동 생성하고 PR까지 이어지는 자동화를 구축해 팀 내 브랜치·PR 문화 정착",
    ],
    achievementsEn: [
      "Fully automated weekly report writing and HRWeb timesheet input that previously took 30min–1hr manually - single command handles Git commits + calendar merge → Excel generation → Gmail delivery",
      "Deployed beyond personal use to Cursor and Claude Desktop for direct invocation - adopted as an active tool by all 10 team members",
      "[Jira·Bitbucket Automation] Creating a ticket still meant manually branching and opening a PR every time → built rule-based automation that creates the branch on ticket status change and carries through to PR creation - established a consistent branch/PR convention across the team",
    ],
  },
  {
    id: "dflow-perf",
    title: "DFLOW MLOps 플랫폼 성능 개선 - 부하테스트 기반 병목 진단",
    titleEn: "DFLOW MLOps Platform Performance - Load-Test-Driven Bottleneck Fix",
    description: "사내 MLOps 라벨링 플랫폼(DFLOW)에 k6·Locust 부하테스트를 도입해 성능 병목을 진단하고, 캐싱과 SQLite WAL 모드로 API 응답 지연을 개선.",
    descriptionEn: "Introduced k6/Locust load testing to an in-house MLOps labeling platform (DFLOW), diagnosed the performance bottleneck, and reduced API latency via caching and SQLite WAL mode.",
    tags: ["Django", "k6", "Locust", "Flask", "SQLite"],
    imageUrl: "/hancominpsace_logo.png",
    status: "deployed",
    type: "company",
    internal: true,
    category: ["backend"],
    company: "한컴인스페이스",
    period: "2026.06 ~ 2026.07",
    role: "성능 개선",
    roleEn: "Performance Engineering",
    longDescription: "라벨링 후 학습·추론까지 이어지는 사내 MLOps 플랫폼 DFLOW의 ML 백엔드 API에 k6·Locust 부하테스트를 도입했습니다. torch 의존성 없는 Flask mock 서버로 GPU 없이도 반복 테스트가 가능한 환경을 만들고, 부하테스트로 드러난 SQLite 동시 쓰기 병목을 캐싱과 WAL 모드로 해결했습니다. 이어서 Webhook 존재 여부 캐싱과 추가 SQLite 프라그마 튜닝으로 최적화를 한 단계 더 진행했습니다.",
    longDescriptionEn: "Introduced k6/Locust load testing to the ML backend API of DFLOW, an in-house MLOps platform spanning labeling through training and inference. Built a torch-free Flask mock server enabling repeatable load tests without GPU access, then resolved the SQLite concurrent-write bottleneck surfaced by testing via caching and WAL mode. Followed up with an additional optimization pass caching webhook existence checks and further tuning SQLite pragmas.",
    details: [],
    roleDetails: [],
    achievements: [
      "[테스트 인프라] GPU 필요한 torch 의존성 때문에 반복 부하테스트가 어려움 → torch 없이 동작하는 Flask ML mock 서버 직접 구현, k6 인증 테스트용 유저·토큰 생성 스크립트 작성",
      "[병목 진단] k6 4개 시나리오로 ML 백엔드 API 부하테스트 - 초기 실패율 23.8%를 API 스펙 오류로 특정해 0.5%까지 수정, 이후 SQLite 동시 쓰기 직렬화를 실제 병목으로 확정",
      "[성능 개선] ML 백엔드 상태를 매번 DB에서 조회·저장하던 구조 → LocMemCache(TTL 30s)로 캐싱하고 값 불변 시 저장 생략, SQLite WAL 모드 적용 - api_load p95 4,239ms→2,106ms(-50%), VU당 DB 쓰기 5회→2회(-60%)",
      "[Webhook 쿼리 스킵] 대부분의 organization이 webhook을 등록하지 않았는데도 이벤트마다 활성 webhook 조회 쿼리가 매번 실행됨 → organization당 활성 webhook 존재 여부를 캐시(TTL 120s)에 저장해 없으면 DB 쿼리 자체를 스킵, mmap_size·wal_autocheckpoint 추가 튜닝으로 SQLite 읽기 처리량 개선",
    ],
    achievementsEn: [
      "[Test Infrastructure] Repeated load testing was blocked by torch's GPU dependency → built a torch-free Flask ML mock server and scripts to provision test users/tokens for k6 auth",
      "[Bottleneck Diagnosis] Ran k6 across 4 scenarios against the ML backend API - traced an initial 23.8% failure rate to API spec mismatches and fixed it down to 0.5%, then confirmed SQLite concurrent-write serialization as the real bottleneck",
      "[Performance Fix] Replaced per-request DB reads/writes for ML backend state checks with LocMemCache (30s TTL) that skips saves when unchanged, plus SQLite WAL mode - api_load p95 4,239ms→2,106ms (-50%), DB writes per VU 5→2 (-60%)",
      "[Webhook Query Skip] Most organizations had zero webhooks registered, yet an active-webhook lookup ran on every event anyway → cached a per-organization has-webhooks flag (120s TTL) to skip the DB query entirely when empty, plus added mmap_size/wal_autocheckpoint tuning for SQLite read throughput",
    ],
  },
  {
    id: "ml-experiment-orchestrator",
    title: "ML 실험 자율 오케스트레이터 - cron · Claude Code 에이전트 설계",
    titleEn: "ML Experiment Autonomous Orchestrator - cron · Claude Code Agent",
    description: "Claude Code를 ML 실험 루프 오케스트레이터로 설계해 반복 엔지니어링을 AI에 위임. cronjob·Skill·Hook·work_history를 조합해 판단→실행→기록→재판단 사이클을 무인 운영.",
    descriptionEn: "Designed Claude Code as an orchestrator for the ML experiment loop, delegating repetitive engineering to the AI. Combined cronjob, Skill, Hook, and work_history to run the decide→run→log→re-decide cycle unattended.",
    tags: ["Claude Code", "Python", "Shell Script", "Slack API", "cron"],
    imageUrl: "/hancominpsace_logo.png",
    status: "deployed",
    type: "company",
    internal: true,
    company: "한컴인스페이스",
    category: ["backend", "ai"],
    period: "2026.05 ~ 2026.06",
    role: "설계 및 개발",
    roleEn: "Design & Development",
    longDescription: "초기화→학습→검증→기록→다음 실험 결정으로 순환하는 ML 실험 루프를 엔지니어가 수동으로 돌려야 했습니다. cronjob으로 Claude Code Skill을 주기 실행해 work_history를 읽고 다음 실험을 판단하게 하고, Hook+sh로 학습을 자동 실행하며, seg·YOLO 학습 이벤트를 감지해 work_history 마크다운에 자동 기록하는 자율 루프를 구성했습니다. AI를 코드 보조가 아니라 반복 엔지니어링 자체를 위임하는 에이전트로 운영한 사내 개인 프로젝트입니다.",
    longDescriptionEn: "The ML experiment loop - init → train → validate → log → decide next - had to be cycled manually by an engineer. Built an autonomous loop: a cron-scheduled Claude Code Skill reads work_history and decides the next experiment, Hook+sh launch training automatically, and a monitor detects seg/YOLO training events and records them to work_history markdown. A personal in-house project running the AI as an agent that owns the repetitive engineering itself, not just code assistance.",
    details: [],
    roleDetails: [
      {
        role: "자율 루프 · 실험 모니터링 설계",
        items: [
          "cronjob으로 Claude Code Skill을 주기 실행 → work_history를 읽고 다음 실험을 판단, Hook+sh로 학습 프로세스 자동 실행 → 결과를 work_history에 기록 → 다음 판단 인풋으로 재투입하는 자율 루프 구성",
          "install_monitor.sh로 학습 모니터 데몬·cron을 서버별 1회 설치 - seg(log.txt·mIoU)와 YOLO(results.csv·mAP50, 헤더명 동적 탐색으로 HBB/OBB 모두 지원)를 각각 감지",
          "best_update·finished·error(CUDA OOM 등)·stopped 이벤트를 감지해 일별 work_history 마크다운에 자동 기록 - 상태파일로 이벤트 중복 기록 방지(cron 매 틱 멱등)",
          "Claude Code Stop 훅으로 매 턴 종료 시 work_history 기록을 강제(세션 sentinel로 턴당 1회만 block해 무한루프 방지), Slack WebHook으로 완료·에러 실시간 알림",
        ],
      },
    ],
    achievements: [
      "[자율 루프] 각 단계 완료 후 사람이 결과를 보고 다음 실험을 결정해야 해 자리를 비우면 실험이 멈춤 → cronjob으로 Claude Code Skill 주기 실행 + Hook+sh 자동 학습 + work_history 재투입 - 엔지니어 개입 없는 연속 실험 가능",
      "[학습 모니터링] 실험 진행·완료·에러를 사람이 로그를 직접 봐야 파악 → install_monitor.sh로 seg(mIoU)·YOLO(mAP50) 자동 감지 데몬·cron 설치, 이벤트를 work_history에 자동 기록 - 예: seg 학습 mIoU 0.39→0.70 전 과정 무인 추적",
      "[기록 강제] 작업 기록이 사람 의지에 의존해 누락 위험 → Claude Code Stop 훅으로 work_history 기록을 강제(sentinel로 턴당 1회, 무한루프 방지) - 실험 이력 유실 방지",
    ],
    achievementsEn: [
      "[Autonomous Loop] Each step required a human to review results and decide the next experiment, so experiments stalled when unattended → cron-scheduled Claude Code Skill + Hook+sh auto-training + work_history re-injection - continuous experiments with no engineer intervention",
      "[Training Monitor] Experiment progress/completion/errors required manually reading logs → install_monitor.sh installs a daemon/cron auto-detecting seg (mIoU) and YOLO (mAP50) events and logging them to work_history - e.g., tracked a seg run's mIoU 0.39→0.70 fully unattended",
      "[Enforced Logging] Work logging depended on human diligence and risked omission → a Claude Code Stop hook enforces work_history logging (once per turn via a sentinel, avoiding infinite loops) - prevents loss of experiment history",
    ],
  },
  {
    id: "ros-detection",
    title: "드론 객체탐지 시스템 - ROS1 → ROS2 마이그레이션",
    titleEn: "Drone Object Detection System - ROS1 to ROS2 Migration",
    description: "RealSense 카메라 기반 드론 객체탐지 시스템을 ROS1 Noetic에서 ROS2 Humble로 마이그레이션. ROS_DOMAIN_ID 기반 멀티 드론 격리 설계, GPU 파이프라인 런타임 오류 해결, 실장비 없는 회귀 검증까지 담당.",
    descriptionEn: "Migrated a RealSense-camera-based drone object detection system from ROS1 Noetic to ROS2 Humble - designed ROS_DOMAIN_ID-based multi-drone isolation, resolved GPU pipeline runtime errors, and built hardware-free regression tests.",
    tags: ["ROS2", "rclpy", "Python", "Docker", "PyTorch", "pytest"],
    imageUrl: "/hancominpsace_logo.png",
    status: "deployed",
    type: "company",
    category: ["backend"],
    company: "한컴인스페이스",
    period: "2026.07",
    role: "ROS2 마이그레이션 설계 및 구현",
    roleEn: "ROS2 Migration Design & Implementation",
    longDescription: "드론에 탑재된 RealSense 카메라로 폭발물·화재·부상자 등을 탐지해 3D 좌표로 변환, GCS에 전송하는 시스템입니다. 핵심 탐지 모델과 좌표 변환 로직은 팀원이 작성했고, 저는 먼저 시스템 전체 아키텍처를 역분석해 문서화하고 순수 로직 단위 테스트·통합 테스트를 추가한 뒤, ROS1 Noetic(catkin)에서 ROS2 Humble(colcon/ament)로의 마이그레이션을 설계·구현했습니다. ROS2에는 ROS1의 Master 개념이 없어, 기존 '프로세스당 마스터 격리'로 여러 드론을 동시에 서빙하던 구조를 ROS_DOMAIN_ID 기반으로 재설계해야 했습니다.",
    longDescriptionEn: "A system where a drone-mounted RealSense camera detects bombs, fires, injured people, etc., converts detections to 3D coordinates, and transmits them to a ground control station. A teammate wrote the core detection model and coordinate-transform logic; I first reverse-engineered and documented the full system architecture and added pure-logic unit tests plus an integration test, then designed and implemented the migration from ROS1 Noetic (catkin) to ROS2 Humble (colcon/ament). ROS2 has no ROS1-style Master concept, so the existing 'one master per process' architecture serving multiple drones concurrently had to be redesigned around ROS_DOMAIN_ID.",
    details: [],
    roleDetails: [],
    achievements: [
      "[멀티 드론 격리 재설계] ROS2엔 Master 개념이 없어 기존 프로세스당-ROS_MASTER_URI로 드론을 격리하던 구조를 유지할 방법이 없었음 → domain_map.py로 드론 IP를 ROS_DOMAIN_ID로 매핑(명시적 설정 우선, 없으면 IP 마지막 옥텟에서 결정론적 파생, 0~101 유효 범위로 클램프)하는 순수 로직 모듈을 설계·단위 테스트로 검증 - 기존 프로세스당-격리 아키텍처를 그대로 재사용",
      "[패키지 전체 이식] catkin/package.xml format2/rospy 기반 두 패키지(explore_msgs, detector)를 colcon/format3/rclpy로 전환 → 메시지 생성을 rosidl로, 노드를 rclpy.node.Node 상속 구조로 재작성, 하드코딩된 /catkin_ws 절대경로를 DETECTOR_ROOT 환경변수 기반으로 파라미터화",
      "[Docker GPU 파이프라인 디버깅] Ubuntu 22.04+ROS2 Humble 이미지로 풀빌드 후 실제 GPU 결합 테스트에서 런타임 오류 2건 발견 → torch import 시 HPC-X UCX 심볼 로딩 순서 문제를 LD_PRELOAD 재정렬로 해결, opencv 4.7 typing 스텁의 cv2.dnn.DictValue 버그를 스텁 무력화로 우회",
      "[안전한 종료 처리] STOP 명령으로 프로세스 종료 시 rclpy spin의 ExternalShutdownException이 처리되지 않아 발생하던 트레이스백과, 무거운 GPU 추론 도중 종료 신호가 오면 무효 컨텍스트에 publish를 시도해 죽는 경쟁 상태 발견 → 정상 종료 경로로 분류 처리하고 publish 직전 가드(_safe_publish)로 두 문제 모두 제거",
      "[실장비 없는 회귀 검증] ROS1→ROS2 API 전면 교체인데 저장소에 자동화 테스트가 전무해 회귀를 잡을 안전망이 없었음 → 좌표 변환·명령 파싱을 rospy 비의존 순수 함수로 분리해 pytest 단위 테스트 작성, synthetic 카메라 메시지로 UDP 명령 수신부터 GPU 추론·MultiTarget 퍼블리시·STOP 종료까지 전체 파이프라인을 재현하는 통합 테스트 추가 - 실 하드웨어 없이 17건 테스트 통과 확인",
    ],
    achievementsEn: [
      "[Multi-Drone Isolation Redesign] ROS2 has no Master concept, so the existing per-process ROS_MASTER_URI isolation for serving multiple drones had no direct equivalent → designed domain_map.py, a pure-logic module mapping drone IPs to ROS_DOMAIN_ID (explicit config first, else deterministically derived from the last IP octet, clamped to the valid 0-101 range), verified with unit tests - reused the existing per-process isolation architecture as-is",
      "[Full Package Port] Ported two packages (explore_msgs, detector) off catkin/package.xml format2/rospy → colcon/format3/rclpy, moving message generation to rosidl and rewriting nodes on rclpy.node.Node, and parameterized a hardcoded /catkin_ws absolute path via a DETECTOR_ROOT env var",
      "[Docker GPU Pipeline Debugging] After a full rebuild on an Ubuntu 22.04 + ROS2 Humble image, a real GPU integration test surfaced 2 runtime errors → fixed an HPC-X UCX symbol load-order issue on torch import via LD_PRELOAD reordering, and worked around an opencv 4.7 typing-stub bug (cv2.dnn.DictValue) by neutralizing the stub",
      "[Clean Shutdown Handling] Found that terminating on a STOP command left rclpy.spin's ExternalShutdownException unhandled (spurious tracebacks), and a race where a shutdown signal arriving mid-inference tried to publish into a dead context → classified the exception as a normal shutdown path and added a pre-publish guard (_safe_publish) to eliminate both",
      "[Hardware-Free Regression Testing] A full ROS1→ROS2 API rewrite with zero existing automated tests meant no safety net for regressions → extracted coordinate-transform and command-parsing logic into rospy-free pure functions with pytest unit tests, then added an integration test replaying the full pipeline (UDP command → spawn → GPU inference → MultiTarget publish → STOP) via synthetic camera messages - verified 17 passing tests with no real hardware",
    ],
  },

  // ── Side projects ──────────────────────────────────────────────────────────
  {
    id: "momentier",
    title: "Momentier",
    description: "여행 중 찍은 사진과 감정을 타임라인으로 기록·공유하는 여행 플래닝 서비스. SWYP 9기 팀 프로젝트.",
    descriptionEn: "Travel planning service for recording and sharing trip photos and emotions as a timeline. SWYP 9th cohort team project.",
    tags: ["Spring Boot", "JWT", "AWS S3", "RDS", "GitHub Actions"],
    imageUrl: "/momentier_thum.png",
    status: "deployed",
    type: "team",
    category: ["backend"],
    period: "2025.01 ~ 2025.03",
    role: "백엔드",
    roleEn: "Backend",
    longDescription: "여행 중 찍은 사진과 감정을 타임라인으로 기록하고 공유하는 여행 플래닝 서비스. SWYP(스위프) 9기 팀 프로젝트로 백엔드 API 설계 및 개발을 담당했습니다.",
    longDescriptionEn: "Travel planning service for recording and sharing trip photos and emotions as a timeline. Responsible for backend API design and development as part of SWYP 9th cohort team project.",
    details: [],
    achievements: ["SWYP 9기 팀 프로젝트 완성 및 배포"],
    achievementsEn: ["Completed and deployed as SWYP 9th cohort team project"],
  },
  {
    id: "chugjibup",
    title: "축지법",
    titleEn: "Chugjibup",
    description: "임장 일정 등록, 매물 비교, 체크리스트 메모까지 한 앱에서. 부동산 임장을 체계적으로 관리하는 서비스. SWYP 10기.",
    descriptionEn: "All-in-one app for scheduling property visits, comparing listings, and managing checklists. A systematic real estate site-visit management service. SWYP 10th cohort.",
    tags: ["Next.js", "TypeScript", "Tailwind CSS", "React Query"],
    imageUrl: "/chukjibeob_thum.webp",
    status: "deployed",
    type: "team",
    category: ["frontend"],
    period: "2025.04 ~ 2025.06",
    role: "프론트엔드",
    roleEn: "Frontend",
    longDescription: "부동산 임장 일정 등록, 매물 비교, 체크리스트 메모를 한 앱에서 관리하는 서비스. SWYP(스위프) 10기 팀 프로젝트로 프론트엔드 개발을 담당했습니다.",
    longDescriptionEn: "Service for managing property visit schedules, listing comparisons, and checklists all in one app. Responsible for frontend development as part of SWYP 10th cohort team project.",
    details: [],
    achievements: ["SWYP 10기 팀 프로젝트 완성"],
    achievementsEn: ["Completed as SWYP 10th cohort team project"],
  },
  {
    id: "wedding",
    title: "위딩",
    titleEn: "Widing",
    description: "결혼 준비 전 과정을 체크리스트·타임라인으로 관리하는 웨딩 플래닝 앱. SWYP 11기 팀 프로젝트.",
    descriptionEn: "Wedding planning app for managing the entire wedding preparation process with checklists and timelines. SWYP 11th cohort team project.",
    tags: ["React Native", "TypeScript", "Expo"],
    imageUrl: "/with-ing_thum.webp",
    status: "deployed",
    type: "team",
    category: ["frontend"],
    period: "2025.07 ~ 2025.10",
    role: "PM · 프론트엔드",
    roleEn: "PM · Frontend",
    longDescription: "결혼 준비 전 과정을 체크리스트와 타임라인으로 관리하는 웨딩 플래닝 앱. SWYP(스위프) 11기 팀 프로젝트로 PM 및 프론트엔드 개발을 담당했습니다.",
    longDescriptionEn: "Wedding planning app for managing the entire wedding preparation process with checklists and timelines. Led PM and frontend development as part of SWYP 11th cohort team project.",
    details: [],
    achievements: ["SWYP 11기 팀 프로젝트 PM · 프론트 주도"],
    achievementsEn: ["Led PM and frontend development for SWYP 11th cohort team project"],
  },
  {
    id: "mapin",
    title: "Mapin",
    description: "위치 기반으로 주변 취향 맞춤 장소를 추천하고 친구와 공유하는 지도 앱. SWYP 앱 4기 팀 프로젝트.",
    descriptionEn: "Location-based map app that recommends nearby places tailored to your taste and lets you share them with friends. SWYP App 4th cohort team project.",
    tags: ["Spring Boot", "PostGIS", "Redis", "AWS", "GitHub Actions"],
    imageUrl: "/swyp-app4_thum.png",
    status: "development",
    type: "team",
    category: ["backend"],
    period: "2026.01 ~ 2026.03",
    role: "백엔드",
    roleEn: "Backend",
    longDescription: "위치 기반으로 주변 취향 맞춤 장소를 추천하고 친구와 공유하는 지도 앱. SWYP(스위프) 앱 4기 팀 프로젝트로 백엔드 API 및 PostGIS 지리 데이터 처리를 담당했습니다.",
    longDescriptionEn: "Location-based map app recommending nearby places tailored to user taste and enabling friend sharing. Led backend API development and PostGIS geospatial data handling as part of SWYP App 4th cohort team project.",
    details: [],
    achievements: ["SWYP 앱 4기 팀 프로젝트 백엔드 주도"],
    achievementsEn: ["Led backend development for SWYP App 4th cohort team project"],
  },
  {
    id: "simvex",
    title: "SIMVEX",
    description: "3D 분해/조립 시뮬레이션과 SSE 스트리밍 AI 어시스턴트를 결합한 기계공학 학습 웹 서비스",
    descriptionEn: "Mechanical engineering learning web service combining 3D disassembly/assembly simulation with SSE streaming AI assistant",
    tags: ["Next.js", "Three.js", "React Three Fiber", "Zustand", "React Query", "Styled Components", "MSW"],
    imageUrl: "/simvex_thum.png",
    link: "https://runtime-simvex.vercel.app/",
    status: "live",
    type: "team",
    category: ["frontend"],
    period: "2026.01",
    role: "프론트엔드 개발",
    roleEn: "Frontend Development",
    longDescription: "제4회 블레이버스 MVP 개발 해커톤에서 진행한 프로젝트입니다. 기계공학 교육에서 2D 교재만으로는 이해하기 어려운 기계 구조를, 3D 인터랙티브 분해·조립 시뮬레이션과 SSE 스트리밍 기반 AI 어시스턴트로 직관적으로 학습할 수 있는 서비스입니다. 7가지 기계 장치(드론, V4 엔진, 로봇팔, 로봇 그리퍼, 판스프링, 만력기, 서스펜션)를 3D로 분해하고 학습할 수 있으며, 부품별 AI 설명·퀴즈·메모·워크플로우·PDF 내보내기까지 학습 흐름 전체를 한 곳에서 관리합니다.",
    longDescriptionEn: "Project from the 4th Blaybus MVP Development Hackathon. A web service that enables intuitive learning of mechanical structures - which are hard to understand from 2D textbooks alone - through 3D interactive disassembly/assembly simulation and SSE streaming AI assistant. Supports 7 mechanical devices (drone, V4 engine, robotic arm, gripper, leaf spring, clamp, suspension) with per-part AI explanations, quizzes, memos, workflow editor, and PDF export all in one place.",
    details: [],
    roleDetails: [
      {
        role: "프론트엔드",
        items: [
          "@react-three/fiber + drei 기반 3D 뷰어 구현 - OrbitControls, Bounds 자동 프레이밍, EffectComposer(Bloom·N8AO·ToneMapping) 후처리",
          "부품 변형(Transform) 충돌 방지를 위한 Outer/Inner 이중 그룹 구조 설계",
          "4개 독립 Zustand 스토어 설계 - ModelStore(분해 레벨·숨김), RenderStore(조명·재질·카메라), EditStore(도구·히스토리), SimulatorStore(재생 타임라인)",
          "Undo/Redo 히스토리 구현 (최대 50개) - Zustand subscribe로 3D 오브젝트 자동 동기화",
          "시뮬레이터 타임라인과 분해 애니메이션 동기화 - useFrame에서 currentTime/duration 비율로 explodeLevel 제어",
          "SSE(Server-Sent Events) 기반 스트리밍 AI 응답 파싱 - ReadableStream + 30ms 인터벌 타이핑 애니메이션 구현",
          "퀴즈 시스템 - 사전 정의 질문 + 부품명 기반 자동 생성으로 문제 풀(Pool) 구성, 매회 5문제 랜덤 출제",
          "jsPDF + html2canvas로 3D 캡처·메모·AI 대화를 하나의 PDF로 내보내기",
          "@xyflow/react 기반 학습 워크플로우 노드 편집",
        ],
      },
    ],
    achievements: [
      "2D 교재만으로는 기계 구조 이해가 어렵다는 교육 한계를 3D 인터랙티브 시뮬레이션으로 해결 - 드론·V4 엔진 등 7가지 기계 장치 분해·조립 학습 콘텐츠 구현",
      "부품이 같은 방향으로 분해되어 겹치는 시각적 충돌 문제를 피보나치 스피어 알고리즘으로 해결 - 모든 부품이 균일하게 퍼지는 자연스러운 분해 애니메이션 구현",
      "AI 응답 대기 중 학습 흐름이 끊기는 문제를 SSE 스트리밍으로 해결 - 응답이 생성되는 즉시 표시해 실시간 학습 몰입감 유지",
      "분산된 학습 도구 간 맥락 전환이 빈번한 문제를 단일 화면 통합 플로우로 해결 - Undo/Redo·퀴즈·메모·워크플로우·PDF 내보내기를 하나의 학습 흐름으로 통합",
    ],
    achievementsEn: [
      "Solved the educational barrier of understanding mechanical structures from 2D textbooks alone via 3D interactive simulation - built disassembly/assembly content for 7 devices including drone and V4 engine",
      "Solved visual collision where parts exploded in the same direction using Fibonacci sphere algorithm - natural disassembly animation with uniform part distribution",
      "Solved learning interruption during AI response wait using SSE streaming - real-time display as responses generate, maintaining learning immersion",
      "Solved frequent context switching between scattered learning tools by integrating into a single-screen unified flow - Undo/Redo, quiz, memo, workflow, and PDF export in one learning stream",
    ],
    resources: [
      { label: "GitHub", url: "https://github.com/team-blaybus-runtime/team-blaybus-runtime_front", type: "link" },
      { label: "프로젝트 설명", url: "https://github.com/team-blaybus-runtime/team-blaybus-runtime_front/blob/main/README.md", type: "link" },
    ],
  },
  {
    id: "pillcare",
    title: "PillCare",
    description: "복약·건강 기록을 한 흐름에 담고, AI가 오늘의 건강 위험을 분석해주는 모바일 헬스케어 앱",
    descriptionEn: "Mobile healthcare app combining medication and health records in one flow, with AI analyzing today's health risk score",
    tags: ["Next.js", "TypeScript", "Tailwind CSS v4", "Zustand", "FastAPI", "PostgreSQL", "Redis", "OpenAI API", "ResNet"],
    imageUrl: "/pillcare_thum.png",
    link: "https://vercel.com/ahnyeongjuns-projects/mfds-2026-frontend-pill-ver",
    status: "live",
    type: "team",
    category: ["fullstack", "ai"],
    period: "2026.05",
    role: "프론트엔드 개발 · UI/UX 디자인 · 백엔드 일부",
    roleEn: "Frontend Development · UI/UX Design · Backend (partial)",
    longDescription: "2026 식약처(MFDS) 공모전 출품작입니다. 복약·건강 기록을 하나의 흐름으로 묶고, AI가 복약 순응도·질환 추이·환경 데이터를 종합해 오늘의 건강 위험 지수를 산출해주는 모바일 헬스케어 앱입니다. 2인 팀으로 진행했으며, 프론트엔드 전담 및 UI/UX 디자인, 백엔드 일부를 담당했습니다.",
    longDescriptionEn: "Submission for the 2026 MFDS (Ministry of Food and Drug Safety) competition. Mobile healthcare app unifying medication and health records in one flow, where AI synthesizes medication adherence, disease trends, and environmental data to calculate a daily Health Risk Index. Built as a 2-person team; responsible for all frontend, UI/UX design, and partial backend.",
    details: [],
    roleDetails: [
      {
        role: "프론트엔드 (Next.js + Zustand)",
        items: [
          "Next.js 16 App Router 기반 전체 UI 설계 및 구현 - 랜딩·온보딩·홈 대시보드·건강 일지·분석·병원 예약·알림 10개 페이지",
          "Zustand 5개 스토어(medications, journals, appointments, health, user)로 전역 상태 관리 - persist 미들웨어로 세션 유지",
          "카카오·구글 OAuth 연동 및 JWT 토큰 관리",
          "Recharts 기반 건강 지수 추이·복약 달성률·증상 패턴 시각화 차트 구현",
        ],
      },
      {
        role: "UI/UX 디자인",
        items: [
          "헬스케어 도메인 특성에 맞춘 정보 계층 설계 - AI 건강 브리핑·오늘 복약·건강 습관 3단 구조의 홈 대시보드",
          "건강 위험 지수(0~100) 시각화 - 수치·색상·아이콘으로 위험도를 직관적으로 전달하는 UI 설계",
        ],
      },
      {
        role: "백엔드 일부 (FastAPI)",
        items: [
          "건강 위험 지수 산출 로직 설계 및 구현 - 복약 순응도(25pts)·질환 추이(25pts)·DUR 안전성(20pts)·증상 추이(15pts)·환경지수(15pts) 5개 도메인 가중합",
          "기상청·에어코리아·식약처 DUR 외부 API 연동 - 실시간 환경 데이터를 건강 알림 트리거에 결합",
        ],
      },
    ],
    achievements: [
      "복약·증상·환경이 분산되어 건강 위험을 한눈에 파악하기 어렵던 문제를 5개 도메인 가중합 건강 위험 지수(Health Index)로 해결 - 복약 순응도·질환 추이·DUR 안전성·증상 추이·환경지수를 0~100 단일 점수로 통합",
      "기상청·에어코리아·식약처 DUR 3종 외부 API를 스케줄러로 주기 수집, 건강 알림 트리거에 환경 데이터 결합 - 고혈압 환자 + 기온 급변 등 컨텍스트 기반 알림 구현",
      "AI Hub ResNet 알약 이미지 분류 모델 추론 파이프라인 구성 - 사진 촬영으로 약품 코드 추론 후 식약처 DUR API 연동해 병용 금기까지 등록 시점에 표시, 낮은 신뢰도 시 직접 검색 유도 폴백 설계",
      "UI/UX 디자인부터 구현까지 전담 - 헬스케어 도메인에 맞는 3단 정보 계층 구조 설계 및 건강 위험도 직관적 시각화",
    ],
    achievementsEn: [
      "Solved fragmented health risk visibility across medication, symptoms, and environment using a 5-domain weighted Health Risk Index - medication adherence, disease trend, DUR safety, symptom trend, and environmental score unified into a 0–100 score",
      "Scheduled collection of 3 external APIs (KMA weather, AirKorea, MFDS DUR) and combined environmental data into health alert triggers - context-aware alerts for scenarios like hypertension + sudden temperature drop",
      "Built AI Hub ResNet pill image classification inference pipeline - photo-to-drug-code inference with MFDS DUR API for contraindication warnings at registration time, with low-confidence fallback to manual search",
      "Sole owner of UI/UX design through implementation - designed 3-tier information hierarchy for healthcare domain and intuitive health risk visualization",
    ],
    resources: [
      { label: "배포", url: "https://vercel.com/ahnyeongjuns-projects/mfds-2026-frontend-pill-ver", type: "link" },
    ],
  },
  {
    id: "deadline-mate",
    title: "DeadlineMate",
    description: "스터디·프로젝트 모임을 개설하고 주간 Todo와 달성률로 팀 목표를 함께 관리하는 모임 플랫폼",
    descriptionEn: "Group platform for creating study/project groups and managing team goals together with weekly todos and completion rates",
    tags: ["Spring Boot", "Java 21", "MySQL", "JPA", "QueryDSL", "JWT", "OAuth", "Spring Event", "JUnit5", "Mockito"],
    imageUrl: "/deadline-mate_thum.png",
    link: "https://completionisland.vercel.app/main",
    status: "live",
    backendActive: true,
    type: "team",
    category: ["backend"],
    period: "2026.03 ~ 2026.04",
    role: "백엔드 개발",
    roleEn: "Backend Development",
    longDescription: "FESI 13기에서 진행한 팀 프로젝트입니다. 스터디나 프로젝트 모임을 개설하고 팀원들과 주간 Todo를 공유하며 달성률을 함께 관리하는 서비스입니다. 11개 도메인을 설계했으며, 모임 검색·신청·알림·평판까지 전체 백엔드 흐름을 담당했습니다.",
    longDescriptionEn: "Team project from FESI 13th cohort. A service for creating study or project groups, sharing weekly todos with teammates, and managing completion rates together. Designed 11 domains and owned the entire backend flow covering group search, applications, notifications, and reputation.",
    details: [],
    roleDetails: [
      {
        role: "모임 & 검색",
        items: [
          "QueryDSL BooleanBuilder + Exists Subquery로 다대다 관계(모임↔카테고리·태그) 동적 필터링 - IN 대신 EXISTS로 불필요한 조인 제거",
          "목록 조회 N+1 제거 - 모임 ID 배치 수집 후 태그·이미지·리더 정보를 IN 쿼리로 각 1회 조회, LinkedHashMap으로 순서 보장",
          "CQRS 분리 - GatheringService(생성·수정·삭제)·GatheringQueryService(목록·상세 조회) 책임 분리, 스케줄러로 일일 RECRUITING→IN_PROGRESS 상태 자동 전환 및 이벤트 발행",
          "PESSIMISTIC_WRITE 락으로 동시 신청 시 maxMembers 초과 방지, Batch UPDATE로 currentMembers 원자적 증감 처리",
        ],
      },
      {
        role: "이벤트 기반 알림",
        items: [
          "@TransactionalEventListener(AFTER_COMMIT)으로 모임 생성·시작·완료·찌르기·평가 5종 이벤트 발행 - 트랜잭션 커밋 후에만 외부 호출하여 데이터 일관성 보장",
          "평판 시스템 이벤트 분리 - 평가 데이터 저장과 userClient 평판 점수 업데이트를 이벤트로 분리해 외부 서비스 실패 시에도 평가 데이터 유실 없는 fault tolerance 확보",
        ],
      },
      {
        role: "인증",
        items: [
          "OAuthClientFactory 패턴으로 Kakao·Google 멀티 프로바이더 통합 - OAuthClient 인터페이스 구현체를 Map으로 관리해 새 제공자 추가 시 클래스 1개만 등록",
          "LoginAttemptService로 로그인 시도 횟수 추적, 임계치 초과 시 잠금 처리로 브루트포스 방어",
        ],
      },
      {
        role: "테스트 & CI",
        items: [
          "51개 테스트 파일 - Controller(단위)·Service(Mockito BDD)·Repository(@DataJpaTest/H2)·E2E(@SpringBootTest) 3-layer 피라미드 구조로 전 도메인 커버",
          "@Nested + @DisplayName 한글 계층 구조로 테스트 의도 명확화, ArgumentCaptor·BDDMockito.given/then 패턴으로 이벤트 발행·상태 변이 검증",
          "GitHub Actions CI - PR → main/dev 머지 전 자동 테스트 실행, H2 테스트 프로파일 분리로 외부 DB 의존성 없는 빌드 환경 구성",
        ],
      },
    ],
    achievements: [
      "전 도메인 51개 테스트 파일 작성 - 단위·통합·E2E 3-layer 구조 + GitHub Actions CI로 PR마다 자동 검증",
      "모임 목록 조회 시 태그·이미지·리더를 건별 조회해 N+1이 발생하던 문제를 IN 쿼리 일괄 처리로 해결 - 4개 테이블 각 1회 쿼리로 최적화",
      "알림 실패가 모임 데이터에 영향을 주는 강결합 구조를 @TransactionalEventListener 이벤트 분리로 해결 - 평가 서비스 장애 시에도 모임 데이터 유실 없는 fault tolerance 확보",
      "동시 신청 시 maxMembers 초과 가능성을 PESSIMISTIC_WRITE + Batch UPDATE로 해결 - 경쟁 조건 없는 원자적 증감 처리",
    ],
    achievementsEn: [
      "Wrote 51 test files across all domains - unit · integration · E2E 3-layer pyramid + GitHub Actions CI for automatic verification on every PR",
      "Solved N+1 on group list queries (per-row tag/image/leader fetches) using IN query batch processing - 4 tables each queried exactly once",
      "Solved tight coupling where notification failures affected group data using @TransactionalEventListener event separation - fault tolerance ensures 0 group data loss even when evaluation service is down",
      "Solved potential maxMembers overflow on concurrent applications with PESSIMISTIC_WRITE + Batch UPDATE - race-condition-free atomic increment/decrement",
    ],
    resources: [
      { label: "서비스", url: "https://completionisland.vercel.app/main", type: "link" },
      { label: "GitHub", url: "https://github.com/FESI13-3/FESI13-backend", type: "link" },
    ],
  },
  {
    id: "concert-reservation",
    title: "동시성 제어 · 이벤트 드리븐 콘서트 예약 시스템",
    titleEn: "Concurrency Control · Event-Driven Concert Reservation System",
    description: "항해99 백엔드코스 - 동시성·이벤트 드리븐·부하 테스트까지 백엔드 핵심 문제를 단계적으로 해결한 프로젝트",
    descriptionEn: "Hanghae99 Backend Course - project solving core backend challenges step by step: concurrency, event-driven architecture, and load testing",
    tags: ["Spring Boot", "Java", "MySQL", "Redis", "Kafka", "k6", "InfluxDB", "Grafana", "JUnit5"],
    status: "deployed",
    type: "personal",
    category: ["backend"],
    hidden: true,
    period: "2025.07 ~ 2025.09",
    role: "백엔드 개발 (항해99 9기)",
    roleEn: "Backend Development (Hanghae99 9th cohort)",
    longDescription: "항해99 백엔드코스 9기에서 진행한 콘서트 예약 시스템입니다. 설계부터 시작해 동시성 제어, 캐싱, 이벤트 드리븐 아키텍처, Kafka 마이그레이션, 부하 테스트까지 10주에 걸쳐 단계적으로 완성했습니다. 상위 10% 수료.",
    longDescriptionEn: "Concert reservation system built during Hanghae99 Backend Course 9th cohort. Progressed step by step over 10 weeks - from initial design through concurrency control, caching, event-driven architecture, Kafka migration, and load testing. Top 10% graduation.",
    details: [],
    roleDetails: [
      {
        role: "동시성 제어",
        items: [
          "좌석 중복 예약 방지를 위해 DB 비관적 락 → Redis 분산락(simple·spin·pub-sub) → 낙관적 락 순으로 전환하며 각 방식의 트레이드오프 직접 검증",
          "k6 + InfluxDB + Grafana로 부하 테스트 수행 - 분산락 재시도 로직이 처리 지연의 주 원인임을 병목으로 특정, 낙관적 락으로 전환해 해결",
        ],
      },
      {
        role: "이벤트 드리븐 & Kafka",
        items: [
          "@TransactionalEventListener(AFTER_COMMIT)으로 예약·결제 이벤트 트랜잭션 경계 밖에서 발행 - 코어 트랜잭션 실패 시 외부 호출 방지",
          "Redis 대기열을 Kafka 토픽으로 전환 - 예약·결제 이벤트를 별도 토픽으로 분리, Redis는 활성 토큰 관리에만 한정",
          "Choreography Saga 패턴 + Redis DLQ로 분산 트랜잭션 실패 시 보상 이벤트 처리",
        ],
      },
      {
        role: "성능 최적화",
        items: [
          "EXPLAIN 기반 슬로우 쿼리 분석 - 카디널리티·사용 패턴 고려한 인덱스 전략 수립으로 쿼리 성능 개선",
          "Redis Sorted Set 기반 실시간 콘서트 랭킹 - 최근 1시간 예약 건수를 스케줄러로 집계, 조회 시 O(log N) 처리",
        ],
      },
    ],
    achievements: [
      "항해99 백엔드코스 9기 상위 10% 수료 - TDD, 이벤트 드리븐 설계, k6 부하 테스트를 실전 프로젝트로 검증",
      "분산락 재시도 로직이 응답 지연의 원인임을 k6+Grafana 부하 테스트로 특정 - 낙관적 락 전환으로 병목 제거",
      "Redis 대기열을 Kafka로 마이그레이션하고 Choreography Saga + DLQ 패턴으로 분산 트랜잭션 일관성 확보",
      "EXPLAIN 기반 인덱스 설계, Redis 캐싱, 비관적·낙관적·분산락 비교 검증까지 백엔드 핵심 문제를 단계적으로 직접 해결",
    ],
    achievementsEn: [
      "Top 10% graduation from Hanghae99 Backend Course 9th cohort - validated TDD, event-driven design, and k6 load testing in a real project",
      "Identified distributed lock retry logic as the root cause of response latency via k6+Grafana load testing - resolved bottleneck by switching to optimistic locking",
      "Migrated Redis queue to Kafka and ensured distributed transaction consistency using Choreography Saga + DLQ pattern",
      "Directly solved core backend challenges step by step - EXPLAIN-based index design, Redis caching, and hands-on comparison of pessimistic, optimistic, and distributed locks",
    ],
    resources: [
      { label: "GitHub", url: "https://github.com/hanghae99-backend/2-SERVICE", type: "link" },
    ],
  },
  {
    id: "booksight",
    title: "Booksight",
    description: "오늘 출간된 책들을 생일처럼 축하하는 서비스",
    descriptionEn: "A service that celebrates books published today as if it were their birthday",
    tags: ["Kotlin", "Spring Boot", "Spring Batch", "QueryDSL", "Redis", "Oracle", "MySQL", "JdbcTemplate"],
    imageUrl: "/booksight_thum.png",
    link: "https://book-web-frontend-one.vercel.app/",
    status: "deployed",
    type: "team",
    category: ["backend"],
    period: "2025.04 ~ 2025.07",
    role: "서브 백엔드 개발",
    roleEn: "Supporting Backend Development",
    longDescription: "매일 수많은 책들이 세상에 태어나고, 그중엔 잊혀지기엔 너무나 특별한 이야기들이 담겨 있습니다. 오늘 처음 세상에 나온 책들을 생일처럼 축하하고, 그 특별한 순간을 함께 나누는 서비스입니다. 6명(프론트엔드 2, 백엔드 2, 디자이너, PM)이 함께 진행했습니다. 국립중앙도서관 API 기반 자동 수집 파이프라인과 12만 건 초기 데이터 안정 적재가 핵심 구현 과제였습니다.",
    longDescriptionEn: "Every day countless books come into the world - some too special to be forgotten. A service that celebrates books making their debut today as if it were their birthday, sharing that special moment together. Team of 6 (2 frontend, 2 backend, 1 designer, 1 PM). Core challenges: automated pipeline via National Library API and stable ingestion of 120,000 initial records.",
    details: [],
    roleDetails: [
      {
        role: "백엔드",
        items: [
          "QueryDSL 기반 동적 검색 쿼리 구현 - 제목·저자·출판사 통합 검색, 동적 정렬",
          "Spring Batch - 국립중앙도서관 API Reader → 카카오 API Processor → DB Writer 파이프라인",
          "external 패키지: CSV → 카카오 API 보강 → JdbcTemplate 배치 적재 파이프라인 (12만 건 초기 데이터 적재)",
          "AOP + Spring Event 기반 검색 로그 수집 및 2차 배치 연동",
          "MySQL + Oracle 듀얼 DB 구성 - 신간 수집·검색 이력 저장에 MySQL, 외부 데이터 소스 연동에 Oracle",
        ],
      },
    ],
    achievements: [
      "12만 건 초기 데이터 적재 시 코루틴·JPA 방식이 OOM으로 실패하는 문제를 JdbcTemplate 배치 INSERT로 전환하여 해결 - 전체 데이터 안정 적재 완료",
      "매일 신간 수집이 중복 실행될 경우 데이터 정합성이 깨지는 문제를 Spring Batch + JobExplorer 중복 실행 방지로 해결 - 국립중앙도서관 API 자동 수집 파이프라인 구축",
      "검색 로그 수집 로직이 비즈니스 코드에 침투해 가독성을 해치는 문제를 AOP + Spring Event로 해결 - 미수집 도서 자동 보강 2차 배치와 비침투 연동",
      "외부 API·CSV 파이프라인이 비즈니스 로직과 혼재되어 유지보수가 어렵던 문제를 external 패키지 분리로 해결 - 외부 연동 변경 시 비즈니스 코드 무영향",
    ],
    achievementsEn: [
      "Solved OOM failures with coroutine/JPA approach during 120,000-record initial ingestion by switching to JdbcTemplate batch INSERT - all data loaded stably",
      "Solved data integrity issues from duplicate daily new-book collection runs using Spring Batch + JobExplorer deduplication - automated National Library API collection pipeline established",
      "Solved search log collection logic polluting business code using AOP + Spring Event - non-invasive integration with secondary batch for auto-enrichment of uncollected books",
      "Solved unmaintainable mixing of external API/CSV pipeline with business logic by extracting external package - business code unaffected when external integrations change",
    ],
    resources: [
      { label: "GitHub", url: "https://github.com/HBD-BookSight", type: "link" },
    ],
  },
];

export function getProjectById(id: string): Project | undefined {
  return projects.find((p) => p.id === id);
}
